import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Privacy Policy — WiseStory",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b">
        <div className="mx-auto flex h-16 max-w-3xl items-center gap-4 px-6">
          <Link
            href="/"
            className="text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <Link href="/" className="flex items-center gap-1.5">
            <Image
              src="/logo-icon.svg"
              alt="WiseStory"
              width={24}
              height={24}
            />
            <span className="text-sm font-semibold">WiseStory</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-2xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 14, 2026
        </p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/80">
          <section>
            <h2 className="text-base font-semibold text-foreground">
              1. Information We Collect
            </h2>
            <p className="mt-2">When you use WiseStory, we collect:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                <strong>Account information:</strong> Your name, email address,
                and profile picture from Google Sign-In.
              </li>
              <li>
                <strong>Google Drive data:</strong> When you connect Google
                Drive, we access files in folders you select (read-only). This
                includes document text, image files, and file metadata.
              </li>
              <li>
                <strong>Usage data:</strong> Campaigns you create, prompts you
                enter, and content generated by the Service.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              2. How We Use Your Information
            </h2>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                <strong>Content generation:</strong> Your Google Drive files are
                processed to build a knowledge base that grounds AI-generated
                content in your brand assets.
              </li>
              <li>
                <strong>Service operation:</strong> Account data is used to
                authenticate you and manage workspace membership.
              </li>
              <li>
                <strong>Improvement:</strong> We may use anonymized usage
                patterns to improve the Service.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              3. Google Drive Data
            </h2>
            <p className="mt-2">
              We request <strong>read-only</strong> access to Google Drive. We:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Only access folders you explicitly select</li>
              <li>
                Extract text content and images for knowledge indexing
              </li>
              <li>Store processed text chunks and embeddings in our database</li>
              <li>Never modify, delete, or share your Drive files</li>
              <li>
                Never transfer your Drive data to third parties
              </li>
            </ul>
            <p className="mt-2">
              You can disconnect Google Drive at any time from your workspace
              settings. Disconnecting removes the stored access tokens. You can
              also request deletion of all indexed data.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              4. AI Processing
            </h2>
            <p className="mt-2">
              Your prompts and brand context are sent to Google Gemini AI models
              for content generation. This processing happens through the Google
              Generative AI API. We do not use your data to train AI models.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              5. Data Storage & Security
            </h2>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                Data is stored on Google Cloud infrastructure (Cloud SQL, Cloud
                Run) in the United States.
              </li>
              <li>
                Database connections are encrypted. Secrets are managed via
                Google Secret Manager.
              </li>
              <li>
                Workspace data is isolated — each workspace can only access its
                own data.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              6. Data Sharing
            </h2>
            <p className="mt-2">
              We do not sell, rent, or share your personal data or content with
              third parties, except:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>
                <strong>Google APIs:</strong> Your data is sent to Google
                services (Gemini, Drive API) as necessary to operate the
                Service.
              </li>
              <li>
                <strong>Legal requirements:</strong> If required by law or to
                protect our rights.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              7. Data Retention
            </h2>
            <p className="mt-2">
              Your data is retained as long as your account is active. You can
              delete campaigns, workspaces, and your account at any time. Upon
              account deletion, all associated data is permanently removed.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              8. Your Rights
            </h2>
            <p className="mt-2">You have the right to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Access your data stored in the Service</li>
              <li>Delete your account and all associated data</li>
              <li>Disconnect Google Drive access at any time</li>
              <li>Request a copy of your data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              9. Cookies
            </h2>
            <p className="mt-2">
              We use essential cookies for authentication and session management.
              We do not use tracking or advertising cookies.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              10. Changes to This Policy
            </h2>
            <p className="mt-2">
              We may update this policy from time to time. We will notify you of
              significant changes by posting a notice on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              11. Contact
            </h2>
            <p className="mt-2">
              For privacy-related questions, contact us at{" "}
              <a
                href="mailto:privacy@wisestory.co"
                className="text-[#f6b900] underline"
              >
                privacy@wisestory.co
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
