import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — WiseStory",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b">
        <div className="mx-auto flex h-16 max-w-3xl items-center gap-4 px-6">
          <Link
            href="/"
            className="text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <Link href="/" className="flex items-center gap-1.5">
            <Image
              src="/logo-icon.svg"
              alt="WiseStory"
              width={24}
              height={24}
            />
            <span className="text-sm font-semibold">WiseStory</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-2xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 14, 2026
        </p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/80">
          <section>
            <h2 className="text-base font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="mt-2">
              By accessing or using WiseStory ("the Service"), you agree to be
              bound by these Terms of Service. If you do not agree, do not use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              2. Description of Service
            </h2>
            <p className="mt-2">
              WiseStory is an AI-powered creative storytelling platform that
              helps teams generate on-brand content by connecting to Google Drive
              and using Google Gemini models. The Service generates text and
              images based on your brand assets and prompts.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              3. Account & Authentication
            </h2>
            <p className="mt-2">
              You sign in using your Google account. You are responsible for
              maintaining the security of your account credentials. You must not
              share your account or allow unauthorized access.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              4. Google Drive Access
            </h2>
            <p className="mt-2">
              The Service requests read-only access to your Google Drive files
              when you choose to connect a workspace. This access is used solely
              to ingest brand assets (documents, images, and other files) for
              content generation. We do not modify, delete, or share your Drive
              files.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              5. Your Content
            </h2>
            <p className="mt-2">
              You retain ownership of all content you upload or connect through
              Google Drive. Content generated by the Service based on your inputs
              is yours to use. We do not claim ownership over your inputs or
              generated outputs.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              6. Acceptable Use
            </h2>
            <p className="mt-2">You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Use the Service for illegal or harmful purposes</li>
              <li>Attempt to reverse-engineer or exploit the Service</li>
              <li>
                Generate content that violates third-party intellectual property
                rights
              </li>
              <li>Abuse, overload, or interfere with the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              7. AI-Generated Content
            </h2>
            <p className="mt-2">
              Content generated by the Service uses Google Gemini AI models.
              While we strive for quality and accuracy, AI-generated content may
              contain errors or inaccuracies. You are responsible for reviewing
              and validating all generated content before use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              8. Limitation of Liability
            </h2>
            <p className="mt-2">
              The Service is provided "as is" without warranties of any kind. We
              are not liable for any damages arising from your use of the
              Service, including but not limited to loss of data, revenue, or
              business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              9. Termination
            </h2>
            <p className="mt-2">
              We may suspend or terminate your access at any time for violation
              of these terms. You may stop using the Service at any time by
              disconnecting your Google Drive and deleting your account.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              10. Changes to Terms
            </h2>
            <p className="mt-2">
              We may update these terms from time to time. Continued use of the
              Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              11. Contact
            </h2>
            <p className="mt-2">
              For questions about these terms, contact us at{" "}
              <a
                href="mailto:support@wisestory.co"
                className="text-[#f6b900] underline"
              >
                support@wisestory.co
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
